-- CREANDO BASE DE DATOS
CREATE DATABASE ControlGemDB;
/*
--USANDO BASE DE DATOS
USE ControlGemDB;

--CREANDO TABLAS
CREATE TABLE OT(
    id INT(8) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ot VARCHAR(15) NOT NULL,
    numPart VARCHAR(15) NOT NULL,
    cantidad INT,
    maquina VARCHAR(60),
    inicio DATE,
    fin DATE
);

--MOSTRAR TABLAS
SHOW TABLES;

--DESCRIBE TABLAS
DESCRIBE OT;*/